/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "surface": "#121316",
        "on-surface": "#e3e2e5",
        "on-surface-variant": "#c4c6cf",
        "surface-dim": "#121316",
        "background": "#121316",
        "on-primary": "#163152",
        "primary-container": "#001f3f",
        "on-error-container": "#ffdad6",
        "on-secondary": "#2f3131",
        "on-secondary-fixed-variant": "#454747",
        "secondary-fixed-dim": "#c6c6c7",
        "inverse-on-surface": "#2f3033",
        "outline-variant": "#43474e",
        "on-background": "#e3e2e5",
        "error": "#ffb4ab",
        "surface-container-high": "#292a2c",
        "on-primary-fixed": "#001c3a",
        "primary-fixed-dim": "#afc8f0",
        "secondary": "#c6c6c7",
        "on-tertiary-fixed": "#002201",
        "outline": "#8e9198",
        "on-tertiary-fixed-variant": "#005306",
        "tertiary-container": "#002501",
        "on-tertiary-container": "#009c14",
        "on-secondary-container": "#b4b5b5",
        "surface-tint": "#afc8f0",
        "surface-container": "#1f2022",
        "surface-container-low": "#1a1c1e",
        "tertiary-fixed": "#75ff68",
        "surface-container-lowest": "#0d0e11",
        "on-tertiary": "#003a03",
        "inverse-primary": "#476083",
        "on-secondary-fixed": "#1a1c1c",
        "primary": "#afc8f0",
        "surface-bright": "#38393c",
        "on-primary-fixed-variant": "#2f486a",
        "surface-container-highest": "#343537",
        "primary-fixed": "#d4e3ff",
        "on-error": "#690005",
        "surface-variant": "#343537",
        "secondary-fixed": "#e2e2e2",
        "inverse-surface": "#e3e2e5",
        "secondary-container": "#454747",
        "on-primary-container": "#6f88ad",
        "tertiary": "#4ce346",
        "tertiary-fixed-dim": "#4ce346"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "24px",
        "stack-lg": "40px",
        "margin-desktop": "64px",
        "touch-target": "48px",
        "margin-mobile": "20px",
        "base": "8px",
        "gutter": "16px",
        "stack-sm": "12px"
      },
      fontFamily: {
        "label-bold": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "label-bold": ["14px", { "lineHeight": "20px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "display-lg-mobile": ["36px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "data-mono": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
