services:
  db:
    image: postgres:16
    container_name: mundial2026_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ic_g8_admin
      POSTGRES_PASSWORD: BD2Obligatorio2026
      POSTGRES_DB: IC_Grupo8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/tablas_mundial2026.sql:/docker-entrypoint-initdb.d/01_tablas.sql
      - ./db/02_seed_if_empty.sql:/docker-entrypoint-initdb.d/02_seed_if_empty.sql
      - ./db/seed_mundial2026.sql:/docker-entrypoint-initdb.d/seed_mundial2026.sql
volumes:
  pgdata: