-- ============================================================
-- SISTEMA DE TICKETING - MUNDIAL 2026
-- Pasaje a tablas desde el MER
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ------------------------------------------------------------
-- PERFIL (entidad padre de la especialización)
-- ------------------------------------------------------------
CREATE TABLE Perfil (
    email               VARCHAR(255)    NOT NULL,
    pais_dir            VARCHAR(100)    NOT NULL,
    localidad           VARCHAR(100)    NOT NULL,
    calle               VARCHAR(150)    NOT NULL,
    numero_dir          VARCHAR(20)     NOT NULL,
    cod_postal          VARCHAR(20)     NOT NULL,
    doc_pais            VARCHAR(100)    NOT NULL,
    doc_tipo            VARCHAR(50)     NOT NULL,
    doc_numero          VARCHAR(50)     NOT NULL,
    password_hash       VARCHAR(255)    NOT NULL,
    CONSTRAINT PK_Perfil PRIMARY KEY (email),
    CONSTRAINT UQ_Perfil_Documento UNIQUE (doc_pais, doc_tipo, doc_numero)
);

-- ------------------------------------------------------------
-- TELEFONO (atributo multivaluado de Perfil)
-- ------------------------------------------------------------
CREATE TABLE Telefono (
    email_perfil        VARCHAR(255)    NOT NULL,
    telefono            VARCHAR(30)     NOT NULL,
    CONSTRAINT PK_Telefono PRIMARY KEY (email_perfil, telefono),
    CONSTRAINT FK_Telefono_Perfil FOREIGN KEY (email_perfil) REFERENCES Perfil(email)
);

-- ------------------------------------------------------------
-- ADMIN (subclase de Perfil)
-- ------------------------------------------------------------
CREATE TABLE Admin (
    email_perfil        VARCHAR(255)    NOT NULL,
    fecha_asignacion    DATE            NOT NULL,
    CONSTRAINT PK_Admin PRIMARY KEY (email_perfil),
    CONSTRAINT FK_Admin_Perfil FOREIGN KEY (email_perfil) REFERENCES Perfil(email)
);

-- ------------------------------------------------------------
-- FUNCIONARIO (subclase de Perfil)
-- ------------------------------------------------------------
CREATE TABLE Funcionario (
    email_perfil        VARCHAR(255)    NOT NULL,
    nro_legajo          VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_Funcionario PRIMARY KEY (email_perfil),
    CONSTRAINT FK_Funcionario_Perfil FOREIGN KEY (email_perfil) REFERENCES Perfil(email),
    CONSTRAINT UQ_Funcionario_Legajo UNIQUE (nro_legajo)
);

-- ------------------------------------------------------------
-- USUARIO (subclase de Perfil)
-- ------------------------------------------------------------
CREATE TABLE Usuario (
    email_perfil        VARCHAR(255)    NOT NULL,
    fecha_registro      DATE            NOT NULL,
    estado_verificacion VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_Usuario PRIMARY KEY (email_perfil),
    CONSTRAINT FK_Usuario_Perfil FOREIGN KEY (email_perfil) REFERENCES Perfil(email)
);


-- ------------------------------------------------------------
-- EQUIPO
-- ------------------------------------------------------------
CREATE TABLE Equipo (
    id_equipo           INT GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR(100)    NOT NULL,
    pais                VARCHAR(100)    NOT NULL,
    CONSTRAINT PK_Equipo PRIMARY KEY (id_equipo)
);

-- ------------------------------------------------------------
-- ESTADIO
-- ------------------------------------------------------------
CREATE TABLE Estadio (
    id_estadio          INT GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR(150)    NOT NULL,
    aforo               INT             NOT NULL,
    pais_dir            VARCHAR(100)    NOT NULL,
    localidad           VARCHAR(100)    NOT NULL,
    calle               VARCHAR(150)    NOT NULL,
    numero_dir          VARCHAR(20)     NOT NULL,
    CONSTRAINT PK_Estadio PRIMARY KEY (id_estadio)
);

-- ------------------------------------------------------------
-- SECTOR (entidad débil de Estadio)
-- ------------------------------------------------------------
CREATE TABLE Sector (
    id_estadio          INT             NOT NULL,
    codigo              VARCHAR(10)     NOT NULL,
    capacidad_maxima    INT             NOT NULL,
    costo               DECIMAL(10,2)   NOT NULL,
    CONSTRAINT PK_Sector PRIMARY KEY (id_estadio, codigo),
    CONSTRAINT FK_Sector_Estadio FOREIGN KEY (id_estadio) REFERENCES Estadio(id_estadio)
);


-- ------------------------------------------------------------
-- EVENTO
-- ------------------------------------------------------------
CREATE TABLE Evento (
    id_evento               INT GENERATED BY DEFAULT AS IDENTITY,
    fecha                   TIMESTAMP        NOT NULL,
    estado                  VARCHAR(50)     NOT NULL,
    id_estadio              INT             NOT NULL,
    email_admin             VARCHAR(255)    NOT NULL,
    id_equipo_local         INT             NOT NULL,
    id_equipo_visitante     INT             NOT NULL,
    CONSTRAINT PK_Evento PRIMARY KEY (id_evento),
    CONSTRAINT FK_Evento_Estadio FOREIGN KEY (id_estadio) REFERENCES Estadio(id_estadio),
    CONSTRAINT FK_Evento_Admin FOREIGN KEY (email_admin) REFERENCES Admin(email_perfil),
    CONSTRAINT FK_Evento_EquipoLocal FOREIGN KEY (id_equipo_local) REFERENCES Equipo(id_equipo),
    CONSTRAINT FK_Evento_EquipoVisitante FOREIGN KEY (id_equipo_visitante) REFERENCES Equipo(id_equipo),
    CONSTRAINT CHK_Evento_Equipos CHECK (id_equipo_local <> id_equipo_visitante)
);

-- ------------------------------------------------------------
-- EVENTO_SECTOR (relación N:N entre Evento y Sector — sectores habilitados)
-- ------------------------------------------------------------
CREATE TABLE Evento_Sector (
    id_evento           INT             NOT NULL,
    id_estadio          INT             NOT NULL,
    codigo_sector       VARCHAR(10)     NOT NULL,
    CONSTRAINT PK_Evento_Sector PRIMARY KEY (id_evento, id_estadio, codigo_sector),
    CONSTRAINT FK_EventoSector_Evento FOREIGN KEY (id_evento) REFERENCES Evento(id_evento),
    CONSTRAINT FK_EventoSector_Sector FOREIGN KEY (id_estadio, codigo_sector) REFERENCES Sector(id_estadio, codigo)
);


-- ------------------------------------------------------------
-- TASA_COMISION (tasa variable a lo largo del tiempo)
-- ------------------------------------------------------------
CREATE TABLE Tasa_Comision (
    id_tasa             INT GENERATED BY DEFAULT AS IDENTITY,
    porcentaje          DECIMAL(5,2)    NOT NULL,
    fecha_desde         DATE            NOT NULL,
    fecha_hasta         DATE,
    CONSTRAINT PK_Tasa_Comision PRIMARY KEY (id_tasa)
);

-- ------------------------------------------------------------
-- VENTA
-- ------------------------------------------------------------
CREATE TABLE Venta (
    id_venta            INT GENERATED BY DEFAULT AS IDENTITY,
    fecha               TIMESTAMP        NOT NULL,
    estado              VARCHAR(50)     NOT NULL,
    monto_total         DECIMAL(10,2)   NOT NULL,
    cantidad_comprada   INT             NOT NULL,
    email_usuario       VARCHAR(255)    NOT NULL,
    id_tasa             INT             NOT NULL,
    CONSTRAINT PK_Venta PRIMARY KEY (id_venta),
    CONSTRAINT FK_Venta_Usuario FOREIGN KEY (email_usuario) REFERENCES Usuario(email_perfil),
    CONSTRAINT FK_Venta_Tasa FOREIGN KEY (id_tasa) REFERENCES Tasa_Comision(id_tasa),
    CONSTRAINT CHK_Venta_Cantidad CHECK (cantidad_comprada BETWEEN 1 AND 5),
    CONSTRAINT CHK_Venta_Estado CHECK (estado IN ('pendiente', 'confirmada', 'paga'))
);

-- ------------------------------------------------------------
-- ENTRADA
-- ------------------------------------------------------------
CREATE TABLE Entrada (
    id_entrada          INT GENERATED BY DEFAULT AS IDENTITY,
    titular             VARCHAR(255)    NOT NULL,
    id_venta            INT             NOT NULL,
    id_evento           INT             NOT NULL,
    id_estadio          INT             NOT NULL,
    codigo_sector       VARCHAR(10)     NOT NULL,
    consumida           BOOLEAN         NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_Entrada PRIMARY KEY (id_entrada),
    CONSTRAINT FK_Entrada_Titular FOREIGN KEY (titular) REFERENCES Usuario(email_perfil),
    CONSTRAINT FK_Entrada_Venta FOREIGN KEY (id_venta) REFERENCES Venta(id_venta),
    CONSTRAINT FK_Entrada_EventoSector FOREIGN KEY (id_evento, id_estadio, codigo_sector)
        REFERENCES Evento_Sector(id_evento, id_estadio, codigo_sector)
);


-- ------------------------------------------------------------
-- TRANSFERENCIA
-- ------------------------------------------------------------
CREATE TABLE Transferencia (
    id_transferencia    INT GENERATED BY DEFAULT AS IDENTITY,
    id_entrada          INT             NOT NULL,
    email_origen        VARCHAR(255)    NOT NULL,
    email_destino       VARCHAR(255)    NOT NULL,
    fecha_solicitud     TIMESTAMP        NOT NULL,
    fecha_aceptacion    TIMESTAMP,
    estado              VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_Transferencia PRIMARY KEY (id_transferencia),
    CONSTRAINT FK_Transferencia_Entrada FOREIGN KEY (id_entrada) REFERENCES Entrada(id_entrada),
    CONSTRAINT FK_Transferencia_Origen FOREIGN KEY (email_origen) REFERENCES Usuario(email_perfil),
    CONSTRAINT FK_Transferencia_Destino FOREIGN KEY (email_destino) REFERENCES Usuario(email_perfil),
    CONSTRAINT CHK_Transferencia_Estado CHECK (estado IN ('pendiente', 'aceptada', 'rechazada')),
    CONSTRAINT CHK_Transferencia_Usuarios CHECK (email_origen <> email_destino)
);

-- ------------------------------------------------------------
-- HISTORIAL_TRANSFERENCIA (log de cadena de custodia de cada entrada)
-- ------------------------------------------------------------
CREATE TABLE Historial_Transferencia (
    id_entrada          INT             NOT NULL,
    id_transferencia    INT             NOT NULL,
    orden               INT             NOT NULL,
    CONSTRAINT PK_Historial PRIMARY KEY (id_entrada, id_transferencia),
    CONSTRAINT FK_Historial_Entrada FOREIGN KEY (id_entrada) REFERENCES Entrada(id_entrada),
    CONSTRAINT FK_Historial_Transferencia FOREIGN KEY (id_transferencia) REFERENCES Transferencia(id_transferencia),
    CONSTRAINT CHK_Historial_Orden CHECK (orden BETWEEN 1 AND 3)
);


-- ------------------------------------------------------------
-- QR (token dinámico por entrada)
-- ------------------------------------------------------------
CREATE TABLE QR (
    token               VARCHAR(255)    NOT NULL,
    id_entrada          INT             NOT NULL,
    generado_en         TIMESTAMP        NOT NULL,
    expira_en           TIMESTAMP        NOT NULL,
    activo              BOOLEAN         NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_QR PRIMARY KEY (token),
    CONSTRAINT FK_QR_Entrada FOREIGN KEY (id_entrada) REFERENCES Entrada(id_entrada)
);

-- ------------------------------------------------------------
-- DISPOSITIVO (dispositivos autorizados para escanear QR)
-- ------------------------------------------------------------
CREATE TABLE Dispositivo (
    id_dispositivo      INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion         VARCHAR(255)    NOT NULL,
    email_funcionario   VARCHAR(255)    NOT NULL,
    CONSTRAINT PK_Dispositivo PRIMARY KEY (id_dispositivo),
    CONSTRAINT FK_Dispositivo_Funcionario FOREIGN KEY (email_funcionario) REFERENCES Funcionario(email_perfil)
);

-- ------------------------------------------------------------
-- VALIDACION (registro de cada escaneo de acceso)
-- ------------------------------------------------------------
CREATE TABLE Validacion (
    id_validacion       INT GENERATED BY DEFAULT AS IDENTITY,
    fecha               TIMESTAMP        NOT NULL,
    id_entrada          INT             NOT NULL,
    token_qr            VARCHAR(255)    NOT NULL,
    id_dispositivo      INT             NOT NULL,
    email_funcionario   VARCHAR(255)    NOT NULL,
    CONSTRAINT PK_Validacion PRIMARY KEY (id_validacion),
    CONSTRAINT FK_Validacion_Entrada FOREIGN KEY (id_entrada) REFERENCES Entrada(id_entrada),
    CONSTRAINT FK_Validacion_QR FOREIGN KEY (token_qr) REFERENCES QR(token),
    CONSTRAINT FK_Validacion_Dispositivo FOREIGN KEY (id_dispositivo) REFERENCES Dispositivo(id_dispositivo),
    CONSTRAINT FK_Validacion_Funcionario FOREIGN KEY (email_funcionario) REFERENCES Funcionario(email_perfil)
);